"""Integration test for the shell-cancellation diagnostic in evaluate_model.

Two adjacent near-redundant shells fitting a field generated by a hidden deeper
source produce a brittle near-cancellation under weak regularization. The
field-based cancellation ratio must (a) be reported, (b) always be >= 1, and
(c) shrink when proper Tikhonov regularization is applied -- the core finding that
the multi-shell "collapse" is an under-regularization artifact, not architecture.
"""

import torch

from vesp.core.kernels import evaluate_kernel
from vesp.core.models import MultiShellDiscreteVESP
from vesp.core.operators import build_joint_operator
from vesp.core.solvers import RidgeSolveConfig, solve_discrete_ridge
from vesp.core.sources import make_shell_sources
from vesp.data.dataset import ResidualGravityData
from vesp.training.evaluate import evaluate_model


def _data_and_sources():
    # model shells are adjacent (near-redundant); the true field comes from a deeper
    # hidden shell the model cannot represent exactly, forcing an approximate fit.
    model_sources = make_shell_sources([0.80, 0.88], [48, 48], body_radius=1.0, dtype=torch.float64)
    hidden = make_shell_sources([0.50], [64], body_radius=1.0, dtype=torch.float64)
    gen = torch.Generator().manual_seed(11)
    directions = torch.randn((600, 3), generator=gen, dtype=torch.float64)
    directions = directions / torch.linalg.norm(directions, dim=-1, keepdim=True)
    radii = 1.1 + 0.4 * torch.rand((600, 1), generator=gen, dtype=torch.float64)
    x = directions * radii
    sigma_hidden = torch.randn(hidden.n_sources, generator=gen, dtype=torch.float64)
    sigma_hidden = sigma_hidden - sigma_hidden.mean()
    out = evaluate_kernel(x, hidden.positions, hidden.weights * sigma_hidden)
    data = ResidualGravityData(
        positions=x, potential=out.potential, acceleration=out.acceleration,
        metadata={"position_units": "normalized"},
    )
    return model_sources, data


def _fit(sources, data, lambda_l2):
    bundle = build_joint_operator(
        data.positions, sources, potential=data.potential, acceleration=data.acceleration,
        use_potential=True, use_acceleration=True, sign=1.0,
    )
    sigma = solve_discrete_ridge(
        bundle.operator, bundle.target, sources.positions, sources.weights, sources.shell_ids,
        RidgeSolveConfig(method="augmented_lstsq", lambda_l2=lambda_l2, column_normalize=True, lambda_moment=0.0),
    )
    model = MultiShellDiscreteVESP(sources, dtype=torch.float64)
    model.set_sigma(sigma)
    return model


def test_cancellation_ratio_reported_and_reduced_by_regularization():
    sources, data = _data_and_sources()
    model_weak = _fit(sources, data, 1.0e-8)
    model_strong = _fit(sources, data, 1.0e1)

    metrics_weak = evaluate_model(model_weak, data, batch_size=512)
    metrics_strong = evaluate_model(model_strong, data, batch_size=512)

    c_weak = metrics_weak["diagnostics"]["shell_cancellation_ratio"]
    c_strong = metrics_strong["diagnostics"]["shell_cancellation_ratio"]

    # the metric is reported and is always >= 1 (Minkowski inequality)
    assert c_weak >= 1.0 and c_strong >= 1.0
    assert "per_shell_field_rms" in metrics_weak["diagnostics"]
    # weak regularization produces a near-cancellation (shells partly cancel)
    assert c_weak > 2.0
    # proper Tikhonov regularization removes it (shells contribute constructively)
    assert c_strong < 1.5
    assert c_strong < c_weak


def test_single_shell_has_no_cancellation_metric():
    sources = make_shell_sources([0.86], [64], body_radius=1.0, dtype=torch.float64)
    gen = torch.Generator().manual_seed(1)
    directions = torch.randn((200, 3), generator=gen, dtype=torch.float64)
    directions = directions / torch.linalg.norm(directions, dim=-1, keepdim=True)
    x = directions * (1.2)
    out = evaluate_kernel(x, sources.positions, sources.weights * torch.ones(sources.n_sources, dtype=torch.float64))
    data = ResidualGravityData(positions=x, potential=out.potential, acceleration=out.acceleration,
                               metadata={"position_units": "normalized"})
    model = MultiShellDiscreteVESP(sources, dtype=torch.float64)
    metrics = evaluate_model(model, data, batch_size=512)
    assert "shell_cancellation_ratio" not in metrics["diagnostics"]
